language: objective-c
scheme: "AppleGuice"
Configuration: "Debug"
before_install:
 - rvm use ruby-2.0.0-p247
 - brew install xctool
script: "xctool clean test -freshInstall -sdk iphonesimulator7.0 -workspace AppleGuice.xcworkspace -scheme AppleGuice -configuration Debug"
