language: objective-c
before_install:
 - export LANG=en_US.UTF-8
 - brew update
 - brew upgrade xctool
 - gem install cocoapods --no-doc
 - pod install
script: "xctool clean test -freshInstall -sdk iphonesimulator7.0 -workspace AppleGuice.xcworkspace -scheme AppleGuice -configuration Debug"
