language: objective-c
scheme: "AppleGuice"
Configuration: "Debug"
before_install:
 - rvm use ruby-2.0.0-p247
 - brew install xctool
 - gem install cocoapods --no-doc
 - cd AppleGuiceTests
 - pod install
script: "xctool test -freshInstall -sdk iphonesimulator -workspace AppleGuiceTests.xcworkspace -scheme AppleGuiceUnitTests -configuration Debug"
